### ISSUE TITLE
Short Tab Rendering

### ISSUE THREAD

**Issue by goossens** [santaclose/ImGuiColorTextEdit#15]
At some point, the ability to render tabs as short arrows was removed from this fork. As a user of Visual Studio Code, I like this feature as it make the editor look cleaner.

In commit https://github.com/goossens/ImGuiColorTextEdit/commit/efe2c5591fbfefaa5651546fa1c9e164a7574d8a, I’ve added it back in to my fork with configurable setting (default is off). Recommend you consider putting it back into this fork.

Let me know if you want a pull request.

**Comment by santaclose** [comment]
sounds reasonable, I was trying to have as simple as possible 😂

**Comment by santaclose** [comment]
submitted https://github.com/santaclose/ImGuiColorTextEdit/commit/a66519a171bb5440c0467ad6779438995ba418d8
